# This file is a template, and might need editing before it works on your project.
# This file is a template, and might need editing before it works on your project.
image: python:latest

before_script:
  - python -V                                   # Print out python version for debugging

test:
  script:
  - python2.7 hamming.py

# run:
#   script:
#   - python setup.py bdist_wheel
#   # an alternative approach is to install and run:
#   - pip install dist/*
#   # run the command here
#   artifacts:
#     paths:
#     - dist/*.whl

# pages:
#   script:
#   - pip install sphinx sphinx-rtd-theme
#   - cd doc ; make html
#   - mv build/html/ ../public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
